### ISSUE TITLE
How stable is gen_emqtt?

### ISSUE THREAD

**Issue by heri16** [erlio/emqtt_commons#1]
How stable is gen_emqtt? Is it maintained? I am looking forward to base an elixir mqtt client library on it.

**Comment by larshesel** [comment]
Hi, gen_emqtt is pretty stable. Just FYI, there already exists an elixir MQTT library built on top of it, namely, https://github.com/gausby/gen_mqtt which is also available on hex.pm, maybe it would make sense to contact Martin Gausby, the maintainer of that Elixir client, to see if a joint effort would be an idea?
