### ISSUE TITLE
Features on README

### ISSUE THREAD

**Issue by heri16** [erlio/emqtt_commons#2]
README should include information similar to the below.
## Features
- Both MQTT V3.1/V3.1.1 Protocol Support
- QoS0, QoS1, QoS2 Publish and Subscribe
- TCP/SSL Socket Support
- Reconnect automatically
- Keepalive and ping/pong
- gen_server like behavior and callbacks

**Comment by heri16** [comment]
- auto resubscribe to topics on reconnect
- back-off retry queue for pending messages when disconnected

**Comment by larshesel** [comment]
Hi again - I failed to notice that your issue before was on this repo. This repo is no longer maintained and was replaced with the vmq_commons repo (https://github.com/erlio/vmq_commons), which among other things contain the gen_emqtt mqtt client behaviour.

Please create PRs there if you would like to improve the documentation.

Thank you.
